/*
    Fixed mission infrastructure and explicit build/permission policy.
    Faction combat content is generated by KPLIB_fnc_applyAutomaticFactionPresets.
*/

FOB_typename = "Land_Cargo_HQ_V1_F";                                     	    // FOB HQ building
FOB_box_typename = "B_Slingload_01_Cargo_F";                      				// FOB Container
FOB_truck_typename = "rhsusf_M1078A1P2_B_WD_CP_fmtv_usarmy";            		// FOB Truck
Arsenal_typename = "B_supplyCrate_F";                							// Arsenal crate
huron_typename = "";                             								// Ops vehicle slot that respawns

KP_liberation_small_storage_building = "ContainmentArea_02_forest_F";     		// Small storage
KP_liberation_large_storage_building = "ContainmentArea_01_forest_F";     		// Large storage
KP_liberation_recycle_building = "Land_Mil_Repair_center_EP1";          		// Salvage depot
KP_liberation_air_vehicle_building = "Land_Airport_01_controlTower_F";  		// Air control object
KP_liberation_heli_slot_building = "Land_HelipadCircle_F";              		// Helicopter slot object
KP_liberation_plane_slot_building = "Land_TentHangar_V1_F";             		// Fixed wing slot object
KP_liberation_supply_crate = "CargoNet_01_box_F";                       		// Supply crate
KP_liberation_ammo_crate = "B_CargoNet_01_ammo_F";                      		// Ammo crate
KP_liberation_fuel_crate = "CargoNet_01_barrels_F";                     		// Fuel crate

// Format: [classname, supplies, ammunition, fuel, optional display name, optional unlock cost]

buildings = [
    ["Land_LampHarbour_F",0,0,0],
    ["Land_LampHalogen_F",0,0,0],
    ["Land_Hlidac_budka",0,0,0,"Sensor Operator Building"],
    ["Camp_EP1",0,0,0,"Sensor Operator Tent"],
	["Base_WarfareBBarrier10xTall",0,0,0,"HESCO Wall Long"],			       // H-Barriers
    ["Land_HBarrierWall6_F",0,0,0,"HESCO Wall Long w/ Ramp"],
    ["Land_HBarrierWall4_F",0,0,0,"HESCO Wall Short w/ Ramp"],
    ["Land_HBarrierWall_corner_F",0,0,0,"HESCO Wall Corner"],
    ["Land_HBarrierWall_corridor_F",0,0,0,"HESCO Corridor"],
    ["Land_HBarrierTower_F",0,0,0,"HESCO Bunker"],
    ["Land_Fort_Watchtower_EP1",0,0,0,"HESCO Tower"],
    ["Land_HBarrier_Big_F",0,0,0,"HESCO Large 4"],
    ["Land_HBarrier_5_F",0,0,0,"HESCO Small 5"],
    ["Land_HBarrier_3_F",0,0,0,"HESCO Small 3"],
    ["Land_HBarrier1",0,0,0,"HESCO Small Single"],
    ["Land_Billboard_F",0,0,0,"Rules Billboard"],					        	// Signs and Billboards
    ["Land_Billboard_03_blank_F",0,0,0,"Admin Billboard"],
    ["Land_Billboard_03_aan_F",0,0,0,"Radios Billboard"],                       // updated
	["Land_Billboard_03_koke_F",0,0,0,"Odin Billboard"],
	["Land_Billboard_03_cheese_F",0,0,0,"Tutorial Billboard"],
    ["Land_Billboard_03_bluking_F",0,0,0,"Karmakut Logo Billboard"],
    ["Land_Billboard_03_ionbase_F",0,0,0,"Karmakut Spread Sheet Radios"],
    ["Land_Billboard_03_lyfe_F",0,0,0,"Karmakut TFAR HELP"],
    ["Land_Billboard_03_argois_F",0,0,0,"Karmakut Insurance"],
    ["Land_Billboard_03_supermarket_F",0,0,0,"Karmakut Role"],
    ["Land_Billboard_03_ygont_F",0,0,0,"Karmakut Builders"],
    ["SignAd_SponsorS_ARMEX_F",0,0,0,"Direction Sign - Resources"],
	["SignAd_SponsorS_Fuel_white_F",0,0,0,"Direction Sign - Arsenal"],
    ["SignAd_SponsorS_F",0,0,0,"Direction Sign - Boat Dock"],
	["SignAd_SponsorS_ION_F",0,0,0,"Direction Sign - Arty Pit"],
    ["SignAd_SponsorS_Suatmm_F",0,0,0,"Direction Sign - Karmakut Arty Pit"],
	["SignAd_SponsorS_Larkin_F",0,0,0,"Direction Sign - CCP"],
	["SignAd_SponsorS_Quontrol_F",0,0,0,"Direction Sign - Helipads"],
	["SignAd_SponsorS_Vrana_F",0,0,0,"Direction Sign - Motor Pool"],
    ["TFAR_Land_Communication_F",500,0,0,"TFAR Signal Repeater (20km)"],
    ["Land_Medevac_house_V1_F",200,0,0,"Medical Building (Small)"],				// Medical Building
    ["Land_Medevac_HQ_V1_F",200,0,0,"Medical Building (Large)"],				// Medical Building
    ["CampEast_EP1",0,0,0,"Squad Tent"],
    ["WarfareBCamp",0,0,0,"HESCO, Sandbag, Camo Net Position"],		        // Fortifications
    ["Fortress2",0,0,0,"Sandbag Bunker w/ Camo Net"],
    ["Land_fortified_nest_big_EP1",0,0,0,"Sandbag Bunker (Large)"],
    ["Fortress1",0,0,0,"Sandbag Guardpost 1"],
    ["Land_fortified_nest_small_EP1",0,0,0,"Sandbag Guardpost 2"],
    ["ShedSmall",0,0,0,"Sandbags w/ Camo Net (Small)"],
    ["Land_fort_artillery_nest",0,0,0],
    ["Land_fort_rampart",0,0,0],
    ["Land_GuardShed",0,0,0,"Guard Shack"],
    ["Hedgehog",0,0,0],
    ["Land_Army_hut_storrage",0,0,0],
    ["Land_jezekbeton",0,0,0],
    ["Land_CncBarrierMedium_F",0,0,0],									// Concrete Stuff
    ["Land_CncBarrierMedium4_F",0,0,0],
    ["Land_Concrete_SmallWall_4m_F",0,0,0],
    ["Land_Concrete_SmallWall_8m_F",0,0,0],
    ["Land_Rampart_F",0,0,0],
    ["Land_RampConcreteHigh_F",0,0,0],
    ["RampConcrete",0,0,0],
    ["BlockConcrete_F",0,0,0],
    ["Land_ConcretePipe_F",0,0,0],
    ["Land_Rail_ConcreteRamp_F",0,0,0],
    ["Land_runway_edgelight",0,0,0,"Runway Edgelight (White)"],
    ["Land_runway_edgelight_blue_F",0,0,0,"Runway Edgelight (Blue)"],
    ["Land_Flush_Light_yellow_F",0,0,0,"Runway Flush Light (Yellow)"],
    ["Land_Flush_Light_green_F",0,0,0,"Runway Flush Light (Green)"],
    ["Land_Flush_Light_red_F",0,0,0,"Runway Flush Light (Red)"],
    ["Land_PortableLight_single_F",0,0,0],								// Lamps
    ["Land_PortableLight_double_F",0,0,0],
    ["Land_HelipadSquare_F",0,0,0,"Helipad Square"],          // Cosmetic Helipad
    ["Land_HelipadRescue_F",0,0,0,"Helipad Rescue H"],
    ["Flag_White_F",0,0,0,"Flag (Karmakut Logo)"],						// Flags
    ["Flag_NATO_F",0,0,0],
    ["Flag_UNO_F",0,0,0,"Flag (United Nations)"],
    ["Flag_US_F",0,0,0],
    ["Flag_CW_US_ARMY",0,0,0],
    ["Flag_CW_US_MARINES",0,0,0],
    ["Flag_CW_US_AIR",0,0,0],
    ["Flag_CW_US_NAVY",0,0,0],
    ["Flag_Red_F",0,0,0],
    ["Flag_Green_F",0,0,0],
    ["Flag_Blue_F",0,0,0],
    ["Flag_FD_Orange_F",0,0,0,"Flag (Orange)"],
    ["Flag_FD_Purple_F",0,0,0,"Flag (Purple)"],
    ["FlagCarrierWhite_EP1",0,0,0,"Flag (White)"],
    ["Flag_RedCrystal_F",0,0,0,"Flag (Medical)"],
    ["CUP_sign_hospital",0,0,0],
    ["Land_SignM_WarningMilitaryArea_english_F",0,0,0],
    ["Land_SignM_WarningMilAreaSmall_english_F",0,0,0],
    ["Land_SignM_WarningMilitaryVehicles_english_F",0,0,0],
    ["Land_Sign_WarningNoWeapon_F",0,0,0],
    ["ITC_Land_loudspeakers2",0,0,0],								    // Flavor Items
    ["USMC_WarfareBUAVterminal",0,0,0,"UAV Terminal (Cosmetic)"],
    ["Land_Mil_Guardhouse",0,0,0],
    ["PowGen_Big_EP1",0,0,0],
    ["CamoNet_BLUFOR_F",0,0,0],
    ["CamoNet_BLUFOR_open_F",0,0,0],
    ["CamoNet_BLUFOR_big_F",0,0,0],
    ["Land_CampingChair_V1_F",0,0,0],
    ["Land_CampingChair_V2_F",0,0,0],
    ["Land_CampingTable_F",0,0,0],
    ["Campfire_burning_F",0,0,0],                                       // Campfire (burning)
    ["MapBoard_altis_F",0,0,0],
    ["MapBoard_stratis_F",0,0,0],
    ["Land_BarGate_F",0,0,0],
    ["Land_Pallet_MilBoxes_F",0,0,0],
    ["Land_PaperBox_open_empty_F",0,0,0],
    ["Land_PaperBox_open_full_F",0,0,0],
    ["Land_PaperBox_closed_F",0,0,0],
    ["Land_DieselGroundPowerUnit_01_F",0,0,0],
    ["Land_ToolTrolley_02_F",0,0,0],
    ["Land_WeldingTrolley_01_F",0,0,0],
    ["Land_Workbench_01_F",0,0,0],
    ["Land_Fuel_tank_big",0,0,0],
    ["Land_Fuel_tank_stairs",0,0,0],
    ["Land_GasTank_01_yellow_F",0,0,0],
    ["Land_GasTank_02_F",0,0,0],
    ["Land_BarrelWater_F",0,0,0],
    ["Land_BarrelWater_grey_F",0,0,0],
    ["Land_WaterBarrel_F",0,0,0],
    ["Land_WaterTank_F",0,0,0],
    ["Land_ClutterCutter_large_F",0,0,0],
    ["Land_Razorwire_F",0,0,0],
    ["Land_Cargo_Tower_V1_F",0,0,0],
    ["Land_Cargo_Patrol_V1_F",0,0,0],
    ["Land_Cargo_Tower_V3_F",0,0,0],
    ["Land_CncShelter_F",0,0,0],
    ["Land_CncWall1_F",0,0,0],
    ["Land_CncWall4_F",0,0,0],
    ["Land_MedicalTent_01_NATO_generic_inner_F",0,0,0],
    ["USMC_WarfareBBarracks",0,0,0],
    ["CUP_A2_Road_PMC_dirt2_25",0,0,0],
    ["CUP_A2_Road_PMC_dirt2_3025",0,0,0],
    ["Land_Rampart_F",0,0,0],                                           // Dirt rampet/and ramps
    ["Dirthump_1_F",0,0,0],
    ["Dirthump_2_F",0,0,0]
];

support_vehicles = [
    [Arsenal_typename,								0,		25,	    0,		"Arsenal Box"],					// Arsenal Box
    ["Land_Cargo40_military_green_F",			    100,	100,	0,		"Resupply Point"], 				// Resupply Point
    [KP_liberation_recycle_building,				200,	0,		0],										// Salvage Depot
    [KP_liberation_air_vehicle_building,			400,	0,		0],										// Flight Control
    [KP_liberation_small_storage_building,			0,		0,		0],										// Small Storage Flat
    [KP_liberation_large_storage_building,			0,		0,		0],										// Large Storage Flat
    [KP_liberation_heli_slot_building,				25,	    0,		0],										// Heli Slot Helipad
    ["karmakut_mpq65",                              250,    0,      0,      "Early Warning Radar"],        	// AN/MPQ-105 Radar
    ["karmakut_tamir",                              1000,  1300,    0,      "Iron Dome"],               	// Iron Dome
    [KP_liberation_plane_slot_building,				250,	0,		0],										// Plane Slot Hangar
    ["ACE_Wheel",									5,		0,		0],										// Spare Wheel
    ["ACE_Track",									5,		0,		0],										// Spare Track
    ["B_Truck_01_flatbed_F",				        150,	0,		150,	"HEMTT Flatbed (Artillery Transport Truck)"],  	            // Cargo Loader Flatbed Nato
    //["Burnes_LCAC_1",        				        250,    50,		200,    "LCAC-Landing Craft Air Cushion"],                        //LCAC
    ["rhsusf_mkvsoc",                               400,    250,    300,    "Mk.V SOC (Assault Transport Boat)"],                       // Mk.V SOC boat
    ["B_Slingload_01_Repair_F",						250,	0,		0,		"Repair Container"],    		// HURON Repair
    ["B_Slingload_01_Ammo_F",						50,		250,	0,		"Ammo Container"],      		// HURON Ammo
	["B_Slingload_01_Fuel_F",						50,		0,		250,	"Fuel Container"],      		// HURON Fuel
    //["rhsusf_M1239_M2_Deploy_socom_d",              300,    300,    300,    "COP Truck"],                   // COP Truck
    [FOB_box_typename,								1500,	0,		400],									// FOB Container
    [FOB_truck_typename,							1800,	0,		500]  									// FOB Truck
];

elite_vehicles = [];
