if (!isServer || {canSuspend}) exitWith {};
params [["_sector", "", [""]], ["_facility", "", [""]]];
private _caller = ["BUILD"] call KPLIB_fnc_permissionRequest;
if (isNull _caller || {!(_sector in blufor_sectors)} || {_caller distance2D getMarkerPos _sector > 100}) exitWith {};
private _kind = ["supply", "ammo", "fuel"] find _facility;
if (_kind < 0) exitWith {};
private _index = KP_liberation_production findIf {(_x select 1) == _sector};
if (_index < 0) exitWith {};
private _record = KP_liberation_production select _index;
if (_record select (4 + _kind)) exitWith {};
private _areas = [getMarkerPos _sector, 100, 1] call KPLIB_fnc_buildStorage;
if (_areas isEqualTo []) exitWith {};
private _prices = [100, 100, 100];
_prices set [_kind, 50];
private _stock = [_areas] call KPLIB_fnc_buildStock;
if ((_prices select 0) > (_stock select 0) || {(_prices select 1) > (_stock select 1)} || {(_prices select 2) > (_stock select 2)}) exitWith {
    [format [localize "STR_PRODUCTION_FACBUILD_ERROR", _prices select 0, _prices select 1, _prices select 2]] remoteExecCall ["hint", owner _caller];
};
[_areas, _prices] call (localNamespace getVariable "KPLIB_buildDebit");
_record set [4 + _kind, true];
recalculate_sectors = true;
[localize "STR_PRODUCTION_FACBUILD_SUCCESS"] remoteExecCall ["hint", owner _caller];
[format ["Built %1 facility at %2", _facility, _sector], "BUILD"] call KPLIB_fnc_log;
