/* Frontline authored strategy data and internal constants.
   Admin-facing options are registered in modules/settings/sections.
   Original mission configuration: https://github.com/KillahPotatoes/KP-Liberation */

BATTLESPACE_TASK_FORCE_SPAWN_MAX_CONCURRENT = 8;

BATTLESPACE_TASK_FORCE_SPAWN_ENTITY_YIELD = 0.01;

BLUFOR_CLUSTER_DISTANCE = 200;

BATTLESPACE_PATHFIND_GRID_SIZE = 100;

BATTLESPACE_PATHFIND_ROAD_SNAP = 900;

BATTLESPACE_PATHFIND_WEIGHT = 1.12;

// Shared soft time budget for each pathfinding worker invocation, in milliseconds.
BATTLESPACE_PATHFIND_BUDGET_MS = 4;

BATTLESPACE_PATHFIND_WORKER_INTERVAL = 0.1;

BATTLESPACE_PATHFIND_MAX_EXPANSIONS = 12000;

BATTLESPACE_PATHFIND_ROAD_MAX_EXPANSIONS = 20000;

BATTLESPACE_PATHFIND_CACHE_TTL = 300;

BATTLESPACE_PATHFIND_CACHE_LIMIT = 128;

BATTLESPACE_PATHFIND_THREAT_RADIUS = 1600;

BATTLESPACE_PATHFIND_FINAL_APPROACH_RADIUS = 600;

BATTLESPACE_PATHFIND_CONGESTION_MULTIPLIER = 1.2;

BATTLESPACE_PATHFIND_VEHICLE_MAX_SLOPE = 0.45;

BATTLESPACE_PATHFIND_INFANTRY_MAX_SLOPE = 1.0;

BATTLESPACE_PATHFIND_RURAL_ROAD_MULTIPLIER = 2.25;

BATTLESPACE_ZEN_ROUTE_SNAPSHOT_POINT_LIMIT = 256;

BATTLESPACE_STRATEGIC_SAVE_INTERVAL = 300;

BATTLESPACE_STRATEGIC_MAX_CONVOYS_PER_TICK = 2;

BATTLESPACE_OFFENSIVE_RETURN_RETRY_INTERVAL = 120;

BATTLESPACE_CONTACT_GROUPS_PER_TICK = 8;

BATTLESPACE_OFFENSIVE_RETARGET_INTERVAL = 30;

BATTLESPACE_OFFENSIVE_FORMATIONS_PER_TICK = 2;

BATTLESPACE_OFFENSIVE_LEG_TIMEOUT = 600;

BATTLESPACE_OFFENSIVE_ARRIVAL_RADIUS = 100;

BATTLESPACE_STRATEGIC_BATTLEGROUP_FORMATIONS = [
    ["INFANTRY", 14, []],
    ["MOTORIZED", 14, ["car"]],
    ["MECHANIZED", 21, ["ifv", "apc"]],
    ["ARMORED", 21, ["tanks", "ifv"]]
];

BATTLESPACE_OFFENSIVE_FORMATION_WEIGHTS = [0.35, 0.35, 0.20, 0.10];

BATTLESPACE_STRATEGIC_DEFENDER_RETURN_RADIUS = 100;

BATTLESPACE_STRATEGIC_EMERGENCY_COOLDOWN = 900;

BATTLESPACE_STRATEGIC_GROUND_FORMATIONS_PER_TICK = 12;

BATTLESPACE_STRATEGIC_DEFENDER_FRONT_FORMATIONS = [
    ["military", 36],
    ["bigtown", 72]
];

BATTLESPACE_STRATEGIC_DEFENDER_ARRIVAL_RADIUS = 100;

BATTLESPACE_STRATEGIC_DEFENDER_ROLES = [
    ["GARRISON", "Garrison", 10],
    ["DEFENSIVE_PATROL", "Defensive Patrol", 8],
    ["RECON_SCREEN", "Reconnaissance Patrol", 8],
    ["AMBUSH", "Ambush Patrol", 8]
];

BATTLESPACE_STRATEGIC_RESERVE_ARRIVAL_RADIUS = 150;

BATTLESPACE_AIRLIFT_LEG_TIMEOUT = 900;

BATTLESPACE_STRATEGIC_DEEP_RECON_PER_TICK = 2;

BATTLESPACE_STRATEGIC_MAX_AIR_RESPONSES_PER_TICK = 1;

BATTLESPACE_STRATEGIC_AIR_RESPONSE_ARRIVAL_RADIUS = 600;

BATTLESPACE_STRATEGIC_AIR_RESPONSE_RETARGET_DISTANCE = 500;

BATTLESPACE_STRATEGIC_MAX_FORTIFICATIONS_PER_TICK = 2;

BATTLESPACE_STRATEGIC_FORTIFICATION_COSTS = [4, 7, 12];

BATTLESPACE_STRATEGIC_FORTIFICATION_MANPOWER_BY_TIER = [4, 5, 7];

BATTLESPACE_STRATEGIC_FORTIFICATION_TERRAIN_TOLERANCE = 0.3;

BATTLESPACE_STRATEGIC_MAX_MINEFIELDS_PER_TICK = 1;

BATTLESPACE_ARTILLERY_POLL_COOLDOWN = 10;

BATTLESPACE_ARTILLERY_FIRE_ORDER_TIMEOUT = 90;

BATTLESPACE_ARTILLERY_TRP_PLAN_INTERVAL = 60;

BATTLESPACE_ARTILLERY_TRP_RELOCATION_DISTANCE = 100;

BATTLESPACE_ARTILLERY_TRP_PRIORITY_BONUS = 100;
