// Default loadoats loosely for each role, should be usable even if grey from some parts not being available to that role
// Default set by Oats, intended to use shared gear and maximise compatibility with any changes
private _StandardUniformContents = [
	["ACE_EarPlugs",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",1],["ACE_CableTie",2],["ACE_packingBandage",5]
];
private _StandardBackpackContents = [
	["ACE_personalAidKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_EarPlugs",3],["kat_Painkiller",5,10]
];
private _StandardInfantryWeapon = [
	"rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],"rhsusf_acc_grip3"
];
private _standardPilotWeapon = [
	"rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],""
];

private _DefaultLoadouts = [
	// Default set by Oats, intended to use shared gear and maximise compatibility with any changes
	["_Default - Officer",              [_StandardInfantryWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP_RTO",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30],["Chemlight_green",2,1]]],"H_tweed_ech_OCP","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad Infantry",       [_StandardInfantryWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30]]],"H_tweed_ech_OCP","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad Autorifleman",   [["rhs_weap_m249_pip","","","rhsusf_acc_su230_mrds",["rhsusf_200Rnd_556x45_mixed_soft_pouch",200],[],"rhsusf_acc_saw_bipod"],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",14],["ACE_quikclot",14],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",2,1],["ACE_SpareBarrel",1,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch",4,200]]],"H_tweed_ech_OCP","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad Grenadier",  	[_StandardInfantryWeapon,[],["rhs_weap_m4a1_carryhandle_m203","","","",["rhs_mag_M433_HEDP",1],[],""],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ItemcTabHCam",1],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",16],["ACE_quikclot",16],["ACE_tourniquet",5],["ACE_splint",4],["ACE_HuntIR_monitor",1],["rhs_mag_an_m8hc",4,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["ACE_HuntIR_M203",1,1],["rhs_mag_M433_HEDP",12,1],["ACE_40mm_Flare_white",10,1],["rhs_mag_m714_White",2,1]]],"MICH2000_Coverall_Ranger_Preset_7","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad SL/TL",          [_StandardInfantryWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP_RTO",_StandardBackpackContents + [["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30],["Chemlight_green",2,1]]],"H_tweed_ech_OCP","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad Medic",          [_StandardInfantryWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",6,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_simc_US_Molle_sturm_OCP",[["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["ACE_plasmaIV",2],["ACE_salineIV",2],["ACE_bloodIV",2],["ACE_bloodIV_500",5],["ACE_plasmaIV_500",6],["ACE_salineIV_500",6],["ACE_salineIV_250",2],["ACE_plasmaIV_250",2],["ACE_bloodIV_250",2],["kat_IV_16",30],["ACE_splint",10],["ACE_tourniquet",15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30],["kat_Carbonate",4,10],["kat_Painkiller",6,10]]],"MICH2000_Coverall_Ranger_Preset_7","rhs_googles_clear",[],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Squad Machine Gunner", [["rhs_weap_m240B","rhsusf_acc_ARDEC_M240","rhsusf_acc_anpeq15side_bk","rhsusf_acc_su230_mrds",["rhsusf_100Rnd_762x51_m80a1epr",250],[],""],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["rhs_mag_an_m8hc",6,1],["ACE_SpareBarrel",1,1],["ACE_EntrenchingTool",1],["kat_Painkiller",4,10]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["rhsusf_100Rnd_762x51_m80a1epr",2,250],["rhsusf_50Rnd_762x51_m61_ap",2,100]]],"H_tweed_ech_OCP","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Vehicle Crew",         [["rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],""],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1]]],["B_AssaultPack_khk",[["ToolKit",1],["ACE_plasmaIV_250",1],["ACE_plasmaIV_500",2],["ACE_salineIV_250",1],["ACE_salineIV_500",2],["ACE_splint",4],["ACE_tourniquet",5],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,5]]],"rhsusf_cvc_green_alt_helmet","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Ogre Engineer",        [["rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],""],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1],["ToolKit",1]]],["B_simc_US_Molle_sturm_OCP_RTO",[["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["MineDetector",1],["kat_Painkiller",3,10],["rhsusf_m112_mag",4,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",2,8]]],"H_MilCap_gry","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Artillery Crew",       [["rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],"rhsusf_acc_grip3"],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",15],["ACE_quikclot",15],["ACE_artilleryTable",1],["ItemcTabHCam",1]]],["B_simc_US_Molle_sturm_OCP_RTO",[["ACE_plasmaIV_250",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_EntrenchingTool",1],["itc_land_tablet_fdc",1],["rhs_mag_an_m8hc",2,1],["ACE_plasmaIV_500",2],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],"H_MilCap_gry","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Pilot Rotary",         [_StandardPilotWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ACE_splint",4],["ACE_tourniquet",5]]],["B_simc_US_Molle_sturm_OCP_RTO",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_personalAidKit",1],["rhs_mag_an_m8hc",4,1],["ACE_HandFlare_White",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],"H_MilCap_gry","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["_Default - Pilot Fixed-Wing ",    [["rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],""],[],[],["USAF_Overalls_Ranger_FG_1_w",_StandardUniformContents],["V_tweed_iotv_mk4_2",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ACE_splint",4],["ACE_tourniquet",5],["rhs_mag_an_m8hc",2,1]]],["tfw_ilbe_blade_gr",_StandardBackpackContents + [["ToolKit",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],"H_PilotHelmetFighter_B","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]]
];

// US ARMY Navy BCT-style loadout originally by Simon Bond#0070 heavily modified by Oats
private _CommunitySealsInfWeapon = [
	"rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],"rhsusf_acc_grip3"
];
private _CommunitySealsSupportWeapon = [
	"rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],"rhsusf_acc_grip3"
];

private _CommunitySealsLoadouts = [
	// US ARMY Navy BCT-style loadout by Simon Bond#0070
	["US ARMY - BCT - 1-6/1-7 PL/PSGT",   [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_whip_ocp",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30],["Chemlight_green",2,1]]],"H_tweed_ech_OCP","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-8 JFO",           [_CommunitySealsInfWeapon,[],["rhs_weap_M320","","","",["rhs_mag_M433_HEDP",1],[],""],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_whip_ocp",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30],["Chemlight_green",2,1]]],"H_tweed_ech_OCP","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-9 PLT Medic",      [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_norepinephrine",10],["kat_phenylephrine",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",4,1],["ACE_packingBandage",10],["ACE_quikclot",10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["tfw_ilbe_whip_ocp",[["kat_AED",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["kat_IV_16",25],["kat_IO_FAST",10],["ACE_splint",10],["ACE_tourniquet",15],["kat_TXA",5],["kat_lidocaine",6],["kat_Carbonate",4,10],["kat_Painkiller",6,10],["ACE_plasmaIV",1],["ACE_salineIV",1],["ACE_bloodIV",1],["ACE_bloodIV_500",3],["ACE_plasmaIV_500",3],["ACE_salineIV_500",3],["ACE_salineIV_250",2],["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30],["ACE_personalAidKit",2]]],"MICH2000_Coverall_Ranger_Preset_7","",[],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-# SL/FTL",              [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP_RTO",_StandardBackpackContents + [["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30],["Chemlight_green",2,1]]],"H_tweed_ech_OCP","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-# FTL",             [_CommunitySealsInfWeapon,[],["rhs_weap_M320","","","",["rhs_mag_M433_HEDP",1],[],""],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ItemcTabHCam",1],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",16],["ACE_quikclot",16],["ACE_tourniquet",5],["ACE_splint",4],["ACE_HuntIR_monitor",1],["rhs_mag_an_m8hc",4,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",10,30],["ACE_HuntIR_M203",1,1],["rhs_mag_M433_HEDP",12,1],["ACE_40mm_Flare_white",10,1],["rhs_mag_m714_White",2,1]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-# Medic",           [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",6,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["B_simc_US_Molle_sturm_OCP",[["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["ACE_plasmaIV",2],["ACE_salineIV",2],["ACE_bloodIV",2],["ACE_bloodIV_500",5],["ACE_plasmaIV_500",6],["ACE_salineIV_500",6],["ACE_salineIV_250",2],["ACE_plasmaIV_250",2],["ACE_bloodIV_250",2],["kat_IV_16",30],["ACE_splint",10],["ACE_tourniquet",15],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30],["kat_Carbonate",4,10],["kat_Painkiller",6,10]]],"milgp_h_opscore_04_khk_hexagon","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-# Rifleman",        [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",15,30]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-# Autorifleman",    [["rhs_weap_m249_pip_S","rhsusf_acc_SFMB556","ACE_acc_pointer_green","rhsusf_acc_su230_mrds",["rhsusf_200Rnd_556x45_box",200],[],"rhsusf_acc_grip4_bipod"],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",14],["ACE_quikclot",14],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",2,1],["ACE_SpareBarrel",1,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch",4,200]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-4 Machine Gunner",   [["rhs_weap_m240B","rhsusf_acc_ARDEC_M240","rhsusf_acc_anpeq15side_bk","rhsusf_acc_su230_mrds",["rhsusf_100Rnd_762x51_m80a1epr",250],[],""],[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["rhs_mag_an_m8hc",6,1],["rhs_mag_m67",2,1],["ACE_SpareBarrel",1,1],["kat_Painkiller",4,10]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["rhsusf_100Rnd_762x51_m80a1epr",2,100],["rhsusf_50Rnd_762x51_m61_ap",2,100]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - 1-4 Asst. Machine Gunner",       [_CommunitySealsInfWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_simc_US_Molle_sturm_OCP",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["ACE_SpareBarrel",1,1],["ACE_WaterBottle",2],["rhsusf_100Rnd_762x51_m80a1epr",1,250],["rhs_mag_30Rnd_556x45_M855A1_PMAG",5,30]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Vehicle Crew",         [_CommunitySealsSupportWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10]]],["rhsusf_spc_crewman",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1],["ACE_personalAidKit",1]]],["B_AssaultPack_cbr",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_splint",4],["ACE_tourniquet",5],["ACE_EarPlugs",3],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",4,5]]],"H_tweed_ech_OCP","",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Ogre Engineer",        [_CommunitySealsSupportWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1]]],["tfw_ilbe_blade_d",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["MineDetector",1],["kat_Painkiller",3,10],["rhsusf_m112_mag",4,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",2,8]]],"H_tweed_ech_OCP","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Ogre Medic",      [_CommunitySealsSupportWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",1,30]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_phenylephrine",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",4,1],["ACE_packingBandage",10],["ACE_quikclot",10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",3,30]]],["tfw_ilbe_whip_ocp",[["kat_AED",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["kat_IV_16",25],["kat_IO_FAST",10],["ACE_splint",10],["ACE_tourniquet",15],["kat_TXA",5],["kat_lidocaine",6],["kat_Carbonate",4,10],["kat_Painkiller",6,10],["ACE_plasmaIV",1],["ACE_salineIV",1],["ACE_bloodIV",1],["ACE_bloodIV_500",3],["ACE_plasmaIV_500",3],["ACE_salineIV_500",3],["ACE_salineIV_250",2],["ACE_personalAidKit",2]]],"MICH2000_Coverall_Ranger_Preset_7","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Savage Gunner",       [_CommunitySealsSupportWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",15],["ACE_quikclot",15],["ACE_artilleryTable",1],["ItemcTabHCam",1]]],["tfw_ilbe_blade_d",[["ACE_plasmaIV_250",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EntrenchingTool",1],["rhs_mag_an_m8hc",2,1],["ACE_EarPlugs",3],["itc_land_tablet_fdc",1],["ACE_plasmaIV_500",2],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],"H_tweed_ech_OCP","",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Pilot Rotary",         [_StandardPilotWeapon,[],[],["U_tweed_acu_summer_ocp",_StandardUniformContents],["V_tweed_iotv_mk4_e_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ToolKit",1],["ACE_splint",4],["ACE_tourniquet",5]]],["tfw_ilbe_whip_mc",[["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_personalAidKit",1],["rhs_mag_an_m8hc",4,1],["ACE_HandFlare_White",1,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG",6,30]]],"rhsusf_hgu56p_visor_green","milgp_f_face_shield_RGR",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]],

	["US ARMY - BCT - Pilot Fixed-Wing",    [["rhs_weap_m4a1_carryhandle_mstock","rhsusf_acc_SF3P556","rhsusf_acc_anpeq15_bk","rhsusf_acc_su230_mrds",["rhs_mag_30Rnd_556x45_M855A1_Stanag_Pull",30],[],""],[],[],["USAF_Overalls_Ranger_FG_1_w",_StandardUniformContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG",1,30]]],["V_tweed_iotv_mk4_2",[["ACE_packingBandage",20],["ItemcTabHCam",1],["ToolKit",1],["ACE_splint",4],["ACE_tourniquet",4],["rhs_mag_an_m8hc",2,1]]],["B_Parachute",[]],"H_PilotHelmetFighter_B","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","rhsusf_ANPVS_14"]]]
];

// Seems to get sorted alphabetically for display
private _DefaultLoadoutsHashmap = createHashMapFromArray(
	_DefaultLoadouts +
	_CommunitySealsLoadouts
);
{
	[_x, _y] call ace_arsenal_fnc_addDefaultLoadout;
} forEach _DefaultLoadoutsHashmap;
