//HEY IF YOU NEED TO CHANGE FACTION PRESETS FILES ARTE HERE: 
// KC_Liberation_Master_Framework\scripts\client\init_client.sqf
// KC_Liberation_Master_Framework\scripts\server\init_server.sqf

// Default loadoats loosely for each role, should be usable even if grey from some parts not being available to that role
// Default set by Oats, intended to use shared gear and maximise compatibility with any changes
private _StandardUniformContents = [
	["ACE_EarPlugs",1],["ACE_microDAGR",1],["ACE_MapTools",1],["ACE_Flashlight_XL50",1],["ACE_IR_Strobe_Item",2],["ACE_CableTie",2],["ACE_epinephrine",2],["ACE_morphine",1],["ACE_packingBandage",5],["ACE_quikclot",5]
];
private _StandardBackpackContents = [
	["ACE_personalAidKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_EarPlugs",3],["kat_Painkiller",5,10]
];
private _StandardInfantryWeapon = [
	"rhs_weap_m4a1_blockII_d","Tier1_RotexIIIC_DE","rhsusf_acc_anpeq16a","Tier1_Eotech551_Desert",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",30],[],"Tier1_GripPod_Tan"
];
private _standardPilotWeapon = ["UK3CB_MP5K_PDW","","","Tier1_Eotech551_Black",["UK3CB_MP5_30Rnd_9x19_Magazine_R",30],[],""];

private _DefaultLoadouts = [
	// Default set by Oats, intended to use shared gear and maximise compatibility with any changes
	//["_Default - Officer",              [_StandardInfantryWeapon,[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_3_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_blade_mc",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30],["Chemlight_green",2,1]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad Infantry",       [_StandardInfantryWeapon,[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad Autorifleman",   [["rhs_weap_m249_pip","","","rhsusf_acc_ACOG_RMR",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"rhsusf_acc_saw_bipod"],[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10]]],["Crye_AVS_1",[["ACE_packingBandage",14],["ACE_quikclot",14],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",2,1],["ACE_SpareBarrel",1,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",4,200]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad FTL/Grenadier",  [_StandardInfantryWeapon,[],["rhs_weap_M320","","","",["rhs_mag_M433_HEDP",1],[],""],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["ItemcTabHCam",1],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_1",[["ACE_packingBandage",16],["ACE_quikclot",16],["ACE_tourniquet",5],["ACE_splint",4],["ACE_HuntIR_monitor",1],["rhs_mag_an_m8hc",4,1],["rhs_mag_m67",2,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",10,30],["ACE_HuntIR_M203",1,1],["rhs_mag_M433_HEDP",12,1],["ACE_40mm_Flare_white",10,1],["rhs_mag_m714_White",2,1]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad SL",             [_StandardInfantryWeapon,[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_3_1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_blade_mc",_StandardBackpackContents + [["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30],["Chemlight_green",2,1]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad Medic",          [_StandardInfantryWeapon,[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["milgp_v_marciras_medic_belt_mc",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",6,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30]]],["B_Kitbag_tan",[["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["ACE_plasmaIV",2],["ACE_salineIV",2],["ACE_bloodIV",2],["ACE_bloodIV_500",5],["ACE_plasmaIV_500",6],["ACE_salineIV_500",6],["ACE_salineIV_250",2],["ACE_plasmaIV_250",2],["ACE_bloodIV_250",2],["kat_IV_16",30],["ACE_splint",10],["ACE_tourniquet",15],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30],["kat_Carbonate",4,10],["kat_Painkiller",6,10]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",[],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Squad Machine Gunner", [["rhs_weap_m240B","rhsusf_acc_ARDEC_M240","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG_RMR",["Tier1_250Rnd_762x51_Belt_M62_Tracer",250],[],""],[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_hgunner_belt_MC",[["ACE_packingBandage",30],["ACE_quikclot",30],["rhs_mag_an_m8hc",6,1],["ACE_SpareBarrel",1,1],["ACE_EntrenchingTool",1],["kat_Painkiller",4,10]]],["B_Kitbag_tan",_StandardBackpackContents + [["Tier1_250Rnd_762x51_Belt_M62_Tracer",2,250],["Tier1_100Rnd_762x51_Belt_M62_Tracer",2,100]]],"milgp_h_opscore_01_RGR","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Vehicle Crew",         [["rhs_weap_M590_5RD","","","",["rhsusf_5Rnd_00Buck",5],[],""],[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["kat_Painkiller",3,10]]],["milgp_v_mmac_light_MC",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1]]],["B_AssaultPack_khk",[["ToolKit",1],["ACE_plasmaIV_250",1],["ACE_plasmaIV_500",2],["ACE_salineIV_250",1],["ACE_salineIV_500",2],["ACE_splint",4],["ACE_tourniquet",5],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["kat_Painkiller",3,10],["rhsusf_5Rnd_00Buck",4,5]]],"rhsusf_cvc_green_alt_helmet","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Ogre Engineer",        [["rhs_weap_M590_8RD","","","",["rhsusf_8Rnd_00Buck",8],[],""],[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_teamleader_belt_rgr",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1],["ToolKit",1]]],["tfw_ilbe_blade_mc",[["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["MineDetector",1],["kat_Painkiller",3,10],["rhsusf_m112_mag",4,1],["rhsusf_8Rnd_00Buck",2,8]]],"H_MilCap_gry","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Artillery Crew",       [["rhs_weap_m4a1_d","","rhsusf_acc_anpeq15_wmx","Tier1_Eotech553_Tan",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",30],[],"Tier1_KAC_VFG_DE"],[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_light_rgr",[["ACE_packingBandage",15],["ACE_quikclot",15],["ACE_artilleryTable",1],["ItemcTabHCam",1]]],["tfw_ilbe_blade_mc",[["ACE_plasmaIV_250",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_EntrenchingTool",1],["itc_land_tablet_fdc",1],["rhs_mag_an_m8hc",2,1],["ACE_plasmaIV_500",2],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",6,30]]],"H_MilCap_gry","rhs_googles_clear",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Pilot Rotary",         [_StandardPilotWeapon,[],[],["USP_G3C_RS_CU_MX_MC",_StandardUniformContents],["milgp_v_mmac_light_MC",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ACE_splint",4],["ACE_tourniquet",5]]],["tfw_ilbe_blade_mc",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_personalAidKit",1],["rhs_mag_an_m8hc",4,1],["ACE_HandFlare_White",1,1],["UK3CB_MP5_30Rnd_9x19_Magazine_R",6,30]]],"H_MilCap_gry","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["_Default - Pilot Fixed-Wing ",    [["UK3CB_MP5K_PDW","","","Tier1_Eotech551_Black",["UK3CB_MP5_30Rnd_9x19_Magazine_R",30],[],""],[],[],["UK3CB_CW_US_B_LATE_U_J_Pilot_Uniform_01_NATO",_StandardUniformContents],["UK3CB_V_Pilot_Vest",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ACE_splint",4],["ACE_tourniquet",5],["rhs_mag_an_m8hc",2,1]]],["tfw_ilbe_blade_gr",_StandardBackpackContents + [["ToolKit",1],["UK3CB_MP5_30Rnd_9x19_Magazine_R",6,30]]],"H_PilotHelmetFighter_B","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]]
];

// Community Navy Seals-style loadout originally by Simon Bond#0070 heavily modified by Oats
private _CommunitySealsInfWeapon = [
	//"rhs_weap_mk18_grip_KAC_d","Tier1_SandmanS_Desert","rhsusf_acc_anpeq16a","rhsusf_acc_acog_d",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",30],[],"Tier1_GripPod_Tan"
];
private _CommunitySealsSupportWeapon = [
	//"rhs_weap_m4a1_d","","rhsusf_acc_anpeq15_wmx","tier1_eotech553_tan",["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",30],[],"rhsusf_acc_kac_grip"
];

private _CommunitySealsLoadouts = [
	// Community Navy Seals-style loadout by Simon Bond#0070
	//["Community - Seals - 1-6/1-7 PL/PSGT",   [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_3_2_AOR1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_whip_d",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30],["Chemlight_green",2,1]]],"rhsusf_opscore_aor1_pelt_nsw","milgp_f_face_shield_tactical_shemagh_khk",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-8 JFO",           [_CommunitySealsInfWeapon,[],["rhs_weap_M320","","","",["rhs_mag_M433_HEDP",1],[],""],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["milgp_v_mmac_teamleader_CB",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_whip_d",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30],["Chemlight_green",2,1]]],"rhsusf_opscore_aor1_pelt_nsw","milgp_f_face_shield_tactical_shemagh_khk",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-9 PLT Medic",      [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["milgp_v_mmac_teamleader_belt_MC",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_norepinephrine",10],["kat_phenylephrine",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",4,1],["ACE_packingBandage",10],["ACE_quikclot",10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30]]],["tfw_ilbe_whip_d",[["kat_AED",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["kat_IV_16",25],["kat_IO_FAST",10],["ACE_splint",10],["ACE_tourniquet",15],["kat_TXA",5],["kat_lidocaine",6],["kat_Carbonate",4,10],["kat_Painkiller",6,10],["ACE_plasmaIV",1],["ACE_salineIV",1],["ACE_bloodIV",1],["ACE_bloodIV_500",3],["ACE_plasmaIV_500",3],["ACE_salineIV_500",3],["ACE_salineIV_250",2],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30],["ACE_personalAidKit",2]]],"rhsusf_opscore_aor1_pelt_nsw","milgp_f_face_shield_tactical_shemagh_khk",[],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-# SL",              [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_3_2_AOR1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["ItemcTabHCam",1],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["tfw_ilbe_blade_mc",_StandardBackpackContents + [["ACE_HuntIR_monitor",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30],["Chemlight_green",2,1]]],"rhsusf_opscore_aor1_pelt_nsw","rhsusf_shemagh_gogg_tan",["ACE_Vector","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-# FTL",             [_CommunitySealsInfWeapon,[],["rhs_weap_M320","","","",["rhs_mag_M433_HEDP",1],[],""],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["ItemcTabHCam",1],["kat_Painkiller",3,10]]],["Crye_AVS_3_3_AOR1",[["ACE_packingBandage",16],["ACE_quikclot",16],["ACE_tourniquet",5],["ACE_splint",4],["ACE_HuntIR_monitor",1],["rhs_mag_an_m8hc",4,1],["rhs_mag_m67",2,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",10,30],["ACE_HuntIR_M203",1,1],["rhs_mag_M433_HEDP",12,1],["ACE_40mm_Flare_white",10,1],["rhs_mag_m714_White",2,1]]],"rhsusf_opscore_aor1_pelt_nsw","rhsusf_shemagh_gogg_tan",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_PVS31_COMPACT"]]],

	//["Community - Seals - 1-# Medic",           [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_MX_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10]]],["milgp_v_marciras_medic_belt_mc",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",6,1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30]]],["B_Kitbag_tan",[["ACE_packingBandage",10],["ACE_quikclot",10],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["ACE_plasmaIV",2],["ACE_salineIV",2],["ACE_bloodIV",2],["ACE_bloodIV_500",5],["ACE_plasmaIV_500",6],["ACE_salineIV_500",6],["ACE_salineIV_250",2],["ACE_plasmaIV_250",2],["ACE_bloodIV_250",2],["kat_IV_16",30],["ACE_splint",10],["ACE_tourniquet",15],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30],["kat_Carbonate",4,10],["kat_Painkiller",6,10]]],"milgp_h_opscore_04_khk_hexagon","milgp_f_face_shield_tactical_shemagh_khk",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-# Rifleman",        [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_1_AOR1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",15,30]]],"rhsusf_opscore_aor1_pelt_nsw","rhsusf_shemagh_gogg_tan",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-# Autorifleman",    [["Tier1_M249_light_S_Desert_vfg3","","Tier1_M249_LA5_M600V_Black","rhsusf_acc_su230a_mrds_c",["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",200],[],"Tier1_SAW_Bipod_KAC_Desert"],[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10]]],["Crye_AVS_1",[["ACE_packingBandage",14],["ACE_quikclot",14],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",2,1],["ACE_SpareBarrel",1,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_WaterBottle",2],["ACE_EntrenchingTool",1],["rhsusf_200Rnd_556x45_mixed_soft_pouch_coyote",4,200]]],"rhsusf_opscore_aor1_pelt_nsw","milgp_f_face_shield_tactical_shemagh_khk",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-4 Machine Gunner",   [["Tier1_MK48_Mod1_Desert","rhsusf_acc_ARDEC_M240","Tier1_Mk48Mod1_LA5_M600V_Black","rhsusf_acc_su230a_mrds_c",["Tier1_250Rnd_762x51_Belt_M62_Tracer",250],[],"Tier1_SAW_Bipod_KAC_Desert"],[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_hgunner_belt_MC",[["ACE_packingBandage",30],["ACE_quikclot",30],["rhs_mag_an_m8hc",6,1],["rhs_mag_m67",2,1],["ACE_SpareBarrel",1,1],["kat_Painkiller",4,10]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["Tier1_250Rnd_762x51_Belt_M62_Tracer",2,250],["Tier1_100Rnd_762x51_Belt_M62_Tracer",2,100]]],"rhsusf_opscore_aor1_pelt_nsw","milgp_f_face_shield_tactical_shemagh_khk",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - 1-4 Asst. Machine Gunner",       [_CommunitySealsInfWeapon,[],[],["USP_G3C_RS_CU_OR_VQ_AOR1",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["Crye_AVS_1_AOR1",[["ACE_packingBandage",20],["ACE_quikclot",20],["ACE_tourniquet",5],["ACE_splint",4],["rhs_mag_an_m8hc",5,1],["rhs_mag_m67",2,1]]],["B_Kitbag_tan",_StandardBackpackContents + [["ACE_EntrenchingTool",1],["ACE_SpareBarrel",1,1],["ACE_WaterBottle",2],["Tier1_250Rnd_762x51_Belt_M62_Tracer",1,250],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",5,30]]],"rhsusf_opscore_aor1_pelt_nsw","rhsusf_shemagh_gogg_tan",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - Vehicle Crew",         [_CommunitySealsSupportWeapon,[],[],["rhs_uniform_FROG01_d",_StandardUniformContents + [["kat_Painkiller",3,10]]],["rhsusf_spc_crewman",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1],["ACE_personalAidKit",1]]],["B_AssaultPack_cbr",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_splint",4],["ACE_tourniquet",5],["ACE_EarPlugs",3],["kat_Painkiller",3,10],["rhsusf_5Rnd_00Buck",4,5]]],"rhsusf_cvc_alt_helmet","milgp_f_face_shield_tactical_khk",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - Ogre Engineer",        [_CommunitySealsSupportWeapon,[],[],["rhs_uniform_FROG01_d",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_teamleader_belt_CB",[["ACE_packingBandage",10],["ACE_quikclot",10],["ItemcTabHCam",1],["rhs_mag_an_m8hc",4,1]]],["tfw_ilbe_blade_d",[["ToolKit",1],["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EarPlugs",3],["ACE_Clacker",1],["ACE_DefusalKit",1],["MineDetector",1],["kat_Painkiller",3,10],["rhsusf_m112_mag",4,1],["rhsusf_8Rnd_00Buck",2,8]]],"rhsusf_mich_helmet_marpatd_alt_headset","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - Ogre Medic",      [_CommunitySealsSupportWeapon,[],[],["rhs_uniform_FROG01_d",_StandardUniformContents + [["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",1,30]]],["milgp_v_marciras_medic_belt_mc",[["ACE_packingBandage",30],["ACE_quikclot",30],["ItemcTabHCam",1],["kat_norepinephrine",10],["kat_nitroglycerin",10],["kat_phenylephrine",10],["kat_naloxone",5],["ACE_surgicalKit",1],["ACE_personalAidKit",1],["ACE_morphine",5],["ACE_epinephrine",5],["ACE_adenosine",5],["rhs_mag_an_m8hc",4,1],["ACE_packingBandage",10],["ACE_quikclot",10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",3,30]]],["tfw_ilbe_whip_d",[["kat_AED",1],["ACE_adenosine",10],["ACE_epinephrine",10],["ACE_EarPlugs",3],["kat_IV_16",25],["kat_IO_FAST",10],["ACE_splint",10],["ACE_tourniquet",15],["kat_TXA",5],["kat_lidocaine",6],["kat_Carbonate",4,10],["kat_Painkiller",6,10],["ACE_plasmaIV",1],["ACE_salineIV",1],["ACE_bloodIV",1],["ACE_bloodIV_500",3],["ACE_plasmaIV_500",3],["ACE_salineIV_500",3],["ACE_salineIV_250",2],["ACE_personalAidKit",2]]],"rhsusf_mich_helmet_marpatd_alt_headset","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - Savage Gunner",       [_CommunitySealsSupportWeapon,[],[],["rhs_uniform_FROG01_d",_StandardUniformContents + [["ACE_splint",4],["ACE_tourniquet",5],["kat_Painkiller",3,10]]],["milgp_v_mmac_light_CB",[["ACE_packingBandage",15],["ACE_quikclot",15],["ACE_artilleryTable",1],["ItemcTabHCam",1]]],["tfw_ilbe_blade_d",[["ACE_plasmaIV_250",2],["ACE_salineIV_250",2],["ACE_salineIV_500",2],["ACE_personalAidKit",1],["ACE_EntrenchingTool",1],["rhs_mag_an_m8hc",2,1],["ACE_EarPlugs",3],["itc_land_tablet_fdc",1],["ACE_plasmaIV_500",2],["kat_Painkiller",3,10],["rhs_mag_30Rnd_556x45_M855A1_PMAG_Tan_Tracer_Red",6,30]]],"rhsusf_mich_helmet_marpatd_alt_headset","milgp_f_face_shield_tactical_khk",["ACE_Vector","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//["Community - Seals - Pilot Rotary",         [_StandardPilotWeapon,[],[],["USP_G3C_RS2_OR_VQ_MC",_StandardUniformContents],["UK3CB_V_Pilot_Vest",[["ACE_packingBandage",20],["ACE_quikclot",20],["ItemcTabHCam",1],["ToolKit",1],["ACE_splint",4],["ACE_tourniquet",5]]],["tfw_ilbe_whip_mc",[["ACE_plasmaIV_250",2],["ACE_plasmaIV_500",4],["ACE_salineIV_250",2],["ACE_salineIV_500",4],["ACE_personalAidKit",1],["rhs_mag_an_m8hc",4,1],["ACE_HandFlare_White",1,1],["UK3CB_MP5_30Rnd_9x19_Magazine_R",6,30]]],"rhsusf_hgu56p_visor_green","milgp_f_face_shield_RGR",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemAndroid","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]],

	//"Community - Seals - Pilot Fixed-Wing",    [["UK3CB_MP5K_PDW","","","Tier1_Eotech551_Black",["UK3CB_MP5_30Rnd_9x19_Magazine_R",30],[],""],[],[],["UK3CB_CW_US_B_LATE_U_J_Pilot_Uniform_01_NATO",_StandardUniformContents + [["UK3CB_MP5_30Rnd_9x19_Magazine_R",1,30]]],["UK3CB_V_Pilot_Vest",[["ACE_packingBandage",20],["ItemcTabHCam",1],["ToolKit",1],["ACE_splint",4],["ACE_tourniquet",4],["rhs_mag_an_m8hc",2,1]]],["B_Parachute",[]],"H_PilotHelmetFighter_B","rhs_googles_clear",["rhsusf_bino_m24","","","",[],[],""],["ItemMap","ItemcTab","TFAR_anprc152","ItemCompass","ItemWatch","USP_GPNVG18_TAN"]]]
];

// Seems to get sorted alphabetically for display
private _DefaultLoadoutsHashmap = createHashMapFromArray(
	_DefaultLoadouts +
	_CommunitySealsLoadouts
);
{
	[_x, _y] call ace_arsenal_fnc_addDefaultLoadout;
} forEach _DefaultLoadoutsHashmap;
