params ["_vehicle"];
_vehicle setPylonLoadout [1,"USAF_PylonRack_1Rnd_ANALQ131", true];
_vehicle setPylonLoadout [2,"USAF_PylonRack_1Rnd_ANAAQ28", true];
_vehicle setPylonLoadout [3,"USAF_PylonRack_1Rnd_AGM65E", true];
_vehicle setPylonLoadout [4,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [5,"USAF_PylonRack_1Rnd_GBU54", true];
_vehicle setPylonLoadout [6,"", true];
_vehicle setPylonLoadout [7,"USAF_PylonRack_1Rnd_GBU54", true];
_vehicle setPylonLoadout [8,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [9,"USAF_PylonRack_1Rnd_AGM65E", true];
_vehicle setPylonLoadout [10,"USAF_PylonRack_7Rnd_APKWS", true];
_vehicle setPylonLoadout [11,"USAF_PylonRack_2Rnd_AIM9X_LAU105", true];