params ["_vehicle"];
_vehicle setPylonLoadout [17,"FIR_AGM88_P_1rnd_M", true];
_vehicle setPylonLoadout [18,"", true];
_vehicle setPylonLoadout [5,"FIR_APKWS_M282_P_7rnd_M", true,[0]];
_vehicle setPylonLoadout [11,"", true,[0]];
_vehicle setPylonLoadout [14,"FIR_APKWS_M247_P_7rnd_M", true,[0]];
_vehicle setPylonLoadout [8,"FIR_APKWS_M247_P_7rnd_M", true,[0]]; 
_vehicle setPylonLoadout [16,"", true];
_vehicle setPylonLoadout [9,"", true]; 
_vehicle setPylonLoadout [1,"FIR_AIM120_F15SE_P_1rnd_M",true];
_vehicle setPylonLoadout [4,"FIR_AIM120_F15SE_P_1rnd_M", true];
_vehicle setPylonLoadout [2,"", true,[0]];
_vehicle setPylonLoadout [3,"", true,[0]];
_vehicle setPylonLoadout [6,"", true,[0]];
_vehicle setPylonLoadout [7,"FIR_GBU12_P_1rnd_M", true];
_vehicle setPylonLoadout [10,"", true];
_vehicle setPylonLoadout [12,"", true,[0]];
_vehicle setPylonLoadout [13,"FIR_GBU12_P_1rnd_M", true];
_vehicle setPylonLoadout [15,"", true,[0]];
_vehicle setPylonLoadout [19,"", true,[0]];
_vehicle setPylonLoadout [20,"FIR_SniperXR_2_P_1rnd_M", true,[0]];