params ["_vehicle"];
_vehicle setPylonLoadout [1,"FIR_AIM120_P_1rnd_M", true];
_vehicle setPylonLoadout [2,"FIR_Scalpel_P_3rnd_M", true];
_vehicle setPylonLoadout [3,"FIR_Mk82_AIR_P_3rnd_M", true];
_vehicle setPylonLoadout [4,"FIR_Mk84_AIR_P_1rnd_M", true];
_vehicle setPylonLoadout [5,"FIR_Mk84_AIR_P_1rnd_M", true];
_vehicle setPylonLoadout [6,"FIR_SniperXR_HTS_P_1rnd_M", true];
_vehicle setPylonLoadout [7,"FIR_Mk84_AIR_P_1rnd_M", true];
_vehicle setPylonLoadout [8,"FIR_Mk82_AIR_P_3rnd_M", true];
_vehicle setPylonLoadout [9,"FIR_Scalpel_P_3rnd_M", true];
_vehicle setPylonLoadout [10,"FIR_AIM120_P_1rnd_M", true];
