params ["_vehicle"];
_vehicle setPylonLoadout [1,"FIR_AIM9X_P_1rnd_M", true];
_vehicle setPylonLoadout [2,"FIR_GBU54_Navy_P_2rnd_M", true];
_vehicle setPylonLoadout [3,"FIR_AGM88_P_1rnd_M", true];
_vehicle setPylonLoadout [4,"FIR_AIM120_P_1rnd_M", true];
_vehicle setPylonLoadout [5,"FIR_Litening_std_P_1rnd_M", true];
_vehicle setPylonLoadout [6,"FIR_ASQ173LST_P_1rnd_M", true];
_vehicle setPylonLoadout [7,"FIR_AGM88_P_1rnd_M", true];
_vehicle setPylonLoadout [8,"FIR_APKWS_M247_P_19rnd_M", true];
_vehicle setPylonLoadout [9,"FIR_AIM9X_P_1rnd_M", true];