params ["_vehicle"];
_vehicle setPylonLoadout [1,"PylonMissile_Missile_BIM9X_x1", true];
_vehicle setPylonLoadout [2,"PylonMissile_Missile_BIM9X_x1", true];
_vehicle setPylonLoadout [3,"rhs_mag_aim120d", true];
_vehicle setPylonLoadout [4,"rhs_mag_aim120d", true];
_vehicle setPylonLoadout [5,"USAF_PylonRack_2Rnd_GBU12_BRU57", true];
_vehicle setPylonLoadout [6,"PylonRack_Missile_AGM_02_x2", true];
_vehicle setPylonLoadout [7,"USAF_PylonRack_2Rnd_AGM154A", true];
_vehicle setPylonLoadout [8,"USAF_PylonRack_2Rnd_AGM154A", true];
_vehicle setPylonLoadout [9,"USAF_Missile_1Rnd_AIM120", true];
_vehicle setPylonLoadout [10,"js_m_fa18_atflir", true];
_vehicle setPylonLoadout [11,"js_m_fa18_wing_tank_x1", true];
_vehicle setPylonLoadout [12,"js_jc_120Rnd_CMChaff_Magazine", true];
_vehicle setPylonLoadout [13,"js_jc_120Rnd_CMChaff_Magazine", true];