params ["_vehicle"];
_vehicle setPylonLoadout [1,"", true];
_vehicle setPylonLoadout [2,"", true];
_vehicle setPylonLoadout [3,"", true];
_vehicle setPylonLoadout [4,"", true];
_vehicle setPylonLoadout [5,"ace_maverick_L_PylonRack_x2", true];
_vehicle setPylonLoadout [6,"ace_maverick_L_PylonRack_x2", true];
_vehicle setPylonLoadout [7,"PylonMissile_Bomb_GBU12_x1", true];
_vehicle setPylonLoadout [8,"PylonMissile_Bomb_GBU12_x1", true];
_vehicle setPylonLoadout [9,"", true];
_vehicle setPylonLoadout [10,"js_m_fa18_atflir", true];
_vehicle setPylonLoadout [11,"", true];